# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [14]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])
a1              

array([1, 2, 3])

In [15]:
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[2, 3, 4],
               [5, 6, 7]])
a2

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
# Create a 3-dimensional Numpy array using np.array()
a3 =np.array([[[3, 4, 2],
               [4, 6, 4],
               [1, 2, 9]],
               [[13, 14, 17],
               [12, 11, 40],
               [8., 5., 6.2]]])
a3

array([[[ 3. ,  4. ,  2. ],
        [ 4. ,  6. ,  4. ],
        [ 1. ,  2. ,  9. ]],

       [[13. , 14. , 17. ],
        [12. , 11. , 40. ],
        [ 8. ,  5. ,  6.2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [25]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape , a1.ndim , a1.size, a1.dtype, type(a1)

((3,), 1, 3, dtype('int32'), numpy.ndarray)

In [26]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.size, a2.dtype, type(a2)

((2, 3), 2, 6, dtype('int32'), numpy.ndarray)

In [27]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.size, a3.dtype, type(a3)

((2, 3, 3), 3, 18, dtype('float64'), numpy.ndarray)

In [28]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a2_array = pd.DataFrame(a2)
a2_array

0  1  2
0  2  3  4
1  5  6  7

In [33]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [46]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random = np.random.randint( 0, 10, size=(7, 2))
array_random

array([[6, 4],
       [4, 3],
       [6, 2],
       [9, 5],
       [2, 7],
       [2, 4],
       [2, 3]])

In [54]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random_2 = np.random.random((3, 5))
array_random_2

array([[0.40936724, 0.60888246, 0.03735114, 0.35886582, 0.37428822],
       [0.00659172, 0.44132302, 0.72905342, 0.89079105, 0.54372996],
       [0.62831954, 0.88243202, 0.1446158 , 0.01491825, 0.95036965]])

In [56]:
# Set the random seed to 42

np.random.seed(seed=42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
array_random_3 = np.random.randint(0, 10, size= (4, 6))
array_random_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [64]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_random_numbers = np.random.randint(10, size=(3, 7))
array_random_numbers

# Find the unique numbers in the array you just created
array_random_numbers[:]

array([[0, 4, 9, 6, 6, 8, 9],
       [9, 2, 6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2, 5, 1]])

In [65]:
# Find the 0'th index of the latest array you created
array_random_numbers[:1]

array([[0, 4, 9, 6, 6, 8, 9]])

In [66]:
# Get the first 2 rows of latest array you created
array_random_numbers[:2]

array([[0, 4, 9, 6, 6, 8, 9],
       [9, 2, 6, 0, 3, 3, 4]])

In [76]:
array_random_numbers.shape

(3, 7)

In [77]:
# Get the first 2 values of the first 2 rows of the latest array
array_random_numbers[:2, :2 ]

array([[0, 4],
       [9, 2]])

In [78]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10, size=(3, 5))
a4

array([[9, 8, 4, 5, 3],
       [9, 6, 8, 6, 0],
       [0, 8, 8, 3, 8]])

In [83]:
ones_array = np.ones((3, 5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
# Add the two arrays together
a4 + ones_array

array([[10.,  9.,  5.,  6.,  4.],
       [10.,  7.,  9.,  7.,  1.],
       [ 1.,  9.,  9.,  4.,  9.]])

In [86]:
# Create another array of ones of shape (5, 3)
ones_array_2 = np.ones((5, 3))
ones_array_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
# Try add the array of ones and the other most recent array together
a4 + ones_array_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [88]:
# Create another array of ones of shape (3, 5)
ones_array_3 = np.ones((3, 5))
ones_array_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
ones_array_2.shape, ones_array_3.shape

((5, 3), (3, 5))

In [91]:
ones_array_2.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
ones_array_2.T.shape

(3, 5)

In [95]:
ones_array_2 = ones_array_2.T

In [96]:
# Subtract the new array of ones from the other most recent array
ones_array_3 - ones_array_2


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
# Multiply the ones array with the latest array
ones_array_2 * ones_array_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
array_random_2


array([[0.40936724, 0.60888246, 0.03735114, 0.35886582, 0.37428822],
       [0.00659172, 0.44132302, 0.72905342, 0.89079105, 0.54372996],
       [0.62831954, 0.88243202, 0.1446158 , 0.01491825, 0.95036965]])

In [98]:
# Take the latest array to the power of 2 using '**'
array_random_2 ** 2

array([[1.67581541e-01, 3.70737850e-01, 1.39510782e-03, 1.28784679e-01,
        1.40091675e-01],
       [4.34507206e-05, 1.94766006e-01, 5.31518891e-01, 7.93508702e-01,
        2.95642269e-01],
       [3.94785445e-01, 7.78686265e-01, 2.09137302e-02, 2.22554120e-04,
        9.03202463e-01]])

In [102]:
# Do the same thing with np.square()
np.square(array_random_2)

array([[1.67581541e-01, 3.70737850e-01, 1.39510782e-03, 1.28784679e-01,
        1.40091675e-01],
       [4.34507206e-05, 1.94766006e-01, 5.31518891e-01, 7.93508702e-01,
        2.95642269e-01],
       [3.94785445e-01, 7.78686265e-01, 2.09137302e-02, 2.22554120e-04,
        9.03202463e-01]])

In [103]:
# Find the mean of the latest array using np.mean()
np.mean(array_random_2)

0.46805995439384057

In [104]:
# Find the maximum of the latest array using np.max()
np.max(array_random_2)

0.9503696453630248

In [105]:
# Find the minimum of the latest array using np.min()
np.min(array_random_2)

0.0065917160612289916

In [106]:
# Find the standard deviation of the latest array
np.std(array_random_3)

2.419538523492996

In [107]:
# Find the variance of the latest array
np.var(array_random_3)

5.854166666666667

In [112]:
# Reshape the latest array to (3, 5, 1)
array_random_2.reshape(3, 5, 1).shape

(3, 5, 1)

In [113]:
array_random_2

array([[0.40936724, 0.60888246, 0.03735114, 0.35886582, 0.37428822],
       [0.00659172, 0.44132302, 0.72905342, 0.89079105, 0.54372996],
       [0.62831954, 0.88243202, 0.1446158 , 0.01491825, 0.95036965]])

In [114]:
# Transpose the latest array
array_random_2.T

array([[0.40936724, 0.00659172, 0.62831954],
       [0.60888246, 0.44132302, 0.88243202],
       [0.03735114, 0.72905342, 0.1446158 ],
       [0.35886582, 0.89079105, 0.01491825],
       [0.37428822, 0.54372996, 0.95036965]])

What does the transpose do?

In [115]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [116]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]])

In [117]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1, mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [124]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

mat3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [125]:
mat4

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [126]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [127]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
mat4.T.shape

(3, 4)

In [128]:
mat4 = mat4.T

In [130]:
mat3.shape

(4, 3)

In [131]:
np.dot(mat3, mat4)

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [134]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
d2 = np.random.randint(10, size=(3,4))
d3 = np.random.randint(10, size=(3,4))
d2

array([[2, 0, 0, 4],
       [5, 5, 6, 8],
       [4, 1, 4, 9]])

In [135]:
d3

array([[8, 1, 1, 7],
       [9, 9, 3, 6],
       [7, 2, 0, 3]])

In [136]:
# Compare the two arrays with '>'
d2 > d3

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [137]:
# Compare the two arrays with '>='
d2 >= d3

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [138]:
# Find which elements of the first array are greater than 7
d2 > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True]])

In [139]:
# Which parts of each array are equal? (try using '==')
d2 == d3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [142]:
# Sort one of the arrays you just created in ascending order
np.sort(d2)

array([[0, 0, 2, 4],
       [5, 5, 6, 8],
       [1, 4, 4, 9]])

In [143]:
# Sort the indexes of one of the arrays you just created
np.argsort(d2)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [145]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(d2)

11

In [146]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(d2)

0

In [147]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(d2, axis =1)

array([3, 3, 3], dtype=int64)

In [148]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(d2, axis =0)

array([0, 0, 0, 0], dtype=int64)

In [152]:
# Create an array of normally distributed random numbers
normal_dist_array = np.random.randn(3, 5)
normal_dist_array

array([[ 0.1333245 ,  0.42689602, -0.01284939, -0.35224831,  0.81946661],
       [ 0.52198773,  1.19725986, -0.38248621,  0.69166192,  0.35388501],
       [ 1.04758534, -0.42389623, -3.51476812, -1.34315673,  1.42550613]])

In [155]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.